# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea6bbf190bc4ccde0667fa0a8ccababd26eebfdbe3f1ac8c37e39ef34db993b3342d1cfa80d94e12fc72f2db228adf53af26c2ef57c56bb8ca21636b1cb5f1a

test:
  secret_key_base: 01bf44fe481c65f4904ceb7b460ca4ee5e0d117ffcdb1b28f4845258ac5703dbae9fba9ed8ffa16fbb84d90ee998c6360513349df38f1d8cb09f8b7e97956a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
